version: '3.8'

services:
  web:
    build: .
    command: gunicorn carrentalsystem.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    environment:
      - DEBUG=False
      - DATABASE_URL=postgres://user:password@db:5432/carrental
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=carrental
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    restart: unless-stopped

  nginx:
    image: nginx:1.21
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    restart: unless-stopped

  celery:
    build: .
    command: celery -A carrentalsystem worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    restart: unless-stopped

  celery-beat:
    build: .
    command: celery -A carrentalsystem beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume: